sudo: required
language: python
python:
  - "3.6"

before_install:
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.jpg)|(.txt)'
   then
     echo "Not running CI since code were not changed."
     exit
   fi

script:
  - pip3 install -r requirements.txt 
  - python3 jsonformatter.py
  - python3 tg-post.py
  
notifications:
  email:
    on_success: never
    on_failure: always


